Repository hashicorp/terraform-provider-tls, pull requests merged in 2022-03, with the labels that each got.

#155 QoL: Enabling Golang static code analysis with `golangci-lint`
  .github/workflows/test.yml
  .golangci.yml
  internal/openssh/lib_test.go
  internal/provider/data_source_public_key.go
  internal/provider/provider.go
  internal/provider/resource_cert_request.go
  internal/provider/resource_certificate.go
  internal/provider/resource_private_key.go
  internal/provider/resource_self_signed_cert.go
  internal/provider/types.go
  internal/provider/util.go
Labels: enhancement, size/M, go, github_actions, QoL

#156 Upgrading to Golang 1.17
  .github/workflows/test.yml
  .go-version
  .golangci.yml
  README.md
  go.mod
  go.sum
Labels: dependencies, size/M

#161 GH Action to link incoming issues and pull-requests to the Terraform DevEx Team board
  .github/workflows/add-content-to-project.yml
Labels: size/S

#162 docs: Remove legacy sidebar features
  website/docs/d/public_key.html.md
  website/docs/d/tls_certificate.html.md
  website/docs/index.html.markdown
  website/docs/r/cert_request.html.md
  website/docs/r/locally_signed_cert.html.md
  website/docs/r/private_key.html.md
  website/docs/r/self_signed_cert.html.md
  website/tls.erb
Labels: documentation, size/S

#165 Update CODEOWNERS with new team name: @hashicorp/terraform-devex
  .github/CODEOWNERS
Labels: size/XS

#169 QoL: Updating all the provider Golang code to include `Description` in preparation of documentation generation
  .go-version
  CHANGELOG.md
  internal/provider/common_cert.go
  internal/provider/data_source_certificate.go
  internal/provider/data_source_certificate_test.go
  internal/provider/data_source_public_key.go
  internal/provider/data_source_tls_certificate.go
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/provider/resource_cert_request.go
  internal/provider/resource_certificate.go
  internal/provider/resource_locally_signed_cert.go
  internal/provider/resource_locally_signed_cert_test.go
  internal/provider/resource_private_key.go
  internal/provider/resource_self_signed_cert.go
  internal/provider/resource_self_signed_cert_test.go
  internal/provider/types.go
  internal/provider/util.go
Labels: size/XL

#170 QoL: wiring up `tfplugindocs` to the code generation
  GNUmakefile
  go.mod
  go.sum
  main.go
  scripts/changelog-links.sh
  scripts/errcheck.sh
  scripts/gofmtcheck.sh
  scripts/gogetcookie.sh
  scripts/make-test-ca.tf
  tools/tools.go
Labels: enhancement, dependencies, size/XL, QoL

#171 QoL: Regenerated doc using `tfplugindocs`
  .github/workflows/test.yml
  README.md
  docs/data-sources/certificate.md
  docs/data-sources/public_key.md
  docs/index.md
  docs/resources/cert_request.md
  docs/resources/locally_signed_cert.md
  docs/resources/private_key.md
  docs/resources/self_signed_cert.md
  examples/data-sources/tls_certificate/data-source.tf
  examples/data-sources/tls_public_key/data-source.tf
  examples/provider/provider.tf
  examples/resources/tls_cert_request/resource.tf
  examples/resources/tls_locally_signed_cert/resource.tf
  examples/resources/tls_private_key/resource.tf
  examples/resources/tls_self_signed_cert/resource.tf
  templates/data-sources/certificate.md.tmpl
  templates/index.md.tmpl
  templates/resources/cert_request.md.tmpl
  templates/resources/locally_signed_cert.md.tmpl
  templates/resources/private_key.md.tmpl
  templates/resources/self_signed_cert.md.tmpl
  website/docs/d/public_key.html.md
  website/docs/d/tls_certificate.html.md
  website/docs/index.html.markdown
  website/docs/r/cert_request.html.md
  website/docs/r/locally_signed_cert.html.md
  website/docs/r/private_key.html.md
  website/docs/r/self_signed_cert.html.md
Labels: documentation, size/XL

#172 Add hc-releases upload-file -upload-name flag to goreleaser configuration
  .goreleaser.yml
Labels: size/XS

#173 Adding support for ED25519 to all the `*_cert` resources
  CHANGELOG.md
  docs/resources/cert_request.md
  docs/resources/locally_signed_cert.md
  docs/resources/self_signed_cert.md
  examples/resources/tls_cert_request/resource.tf
  examples/resources/tls_locally_signed_cert/resource.tf
  examples/resources/tls_self_signed_cert/resource.tf
  internal/provider/common_cert.go
  internal/provider/common_key.go
  internal/provider/data_source_public_key.go
  internal/provider/data_source_public_key_test.go
  internal/provider/resource_cert_request.go
  internal/provider/resource_cert_request_test.go
  internal/provider/resource_locally_signed_cert.go
  internal/provider/resource_locally_signed_cert_test.go
  internal/provider/resource_private_key.go
  internal/provider/resource_self_signed_cert.go
  internal/provider/resource_self_signed_cert_test.go
  internal/provider/types.go
  internal/provider/util.go
Labels: size/XL

#177 Adding `dev_overrides` instructions
  GNUmakefile
  README.md
Labels: size/S
