Repository hashicorp/terraform-provider-tls, pull requests merged in 2022-05, with the labels that each got.

#198 Updating doc for PEM fields that underlying Golang libraries append a `\n` to
  docs/data-sources/public_key.md
  docs/resources/cert_request.md
  docs/resources/locally_signed_cert.md
  docs/resources/private_key.md
  docs/resources/self_signed_cert.md
  internal/provider/common_cert.go
  internal/provider/data_source_public_key.go
  internal/provider/resource_cert_request.go
  internal/provider/resource_private_key.go
Labels: size/M

#200 Remove all uses of `Deprecated:` elements of `terraform-plugin-sdk/v2`
  internal/provider/common_cert.go
  internal/provider/common_key.go
  internal/provider/data_source_certificate.go
  internal/provider/data_source_certificate_test.go
  internal/provider/data_source_public_key.go
  internal/provider/data_source_public_key_test.go
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/provider/resource_cert_request.go
  internal/provider/resource_cert_request_test.go
  internal/provider/resource_locally_signed_cert.go
  internal/provider/resource_locally_signed_cert_test.go
  internal/provider/resource_private_key.go
  internal/provider/resource_private_key_test.go
  internal/provider/resource_self_signed_cert.go
  internal/provider/resource_self_signed_cert_test.go
  main.go
Labels: size/L

#189 support parsing certificate content #4
  CHANGELOG.md
  docs/data-sources/certificate.md
  examples/data-sources/tls_certificate/content-example.tf
  internal/provider/data_source_certificate.go
  internal/provider/data_source_certificate_test.go
  internal/provider/testdata/tls_certs/certificate.pem
  templates/data-sources/certificate.md.tmpl
Labels: size/L

#195 All tests should use `TestCheckFunc` helpers
  .go-version
  README.md
  internal/openssh/lib_test.go
  internal/provider/data_source_public_key_test.go
  internal/provider/fixtures_test.go
  internal/provider/resource_cert_request_test.go
  internal/provider/resource_locally_signed_cert_test.go
  internal/provider/resource_private_key_test.go
  internal/provider/resource_self_signed_cert_test.go
  internal/provider/test_check_func_test.go
  internal/provider/types.go
Labels: size/XL

#178 [DO NOT MERGE] RelAPI Onboarding
  .github/workflows/release.yml
  .goreleaser.yml
  .release/release-metadata.hcl
Labels: size/XS

#207 CI to build against both 1.17 and 1.18 for future-proofing
  .github/workflows/test.yml
Labels: size/XS

#209 Allow empty or absent `subject` block
  .golangci.yml
  CHANGELOG.md
  GNUmakefile
  docs/resources/cert_request.md
  docs/resources/self_signed_cert.md
  internal/provider/common_cert.go
  internal/provider/resource_cert_request.go
  internal/provider/resource_cert_request_test.go
  internal/provider/resource_locally_signed_cert.go
  internal/provider/resource_locally_signed_cert_test.go
  internal/provider/resource_self_signed_cert.go
  internal/provider/resource_self_signed_cert_test.go
  internal/provider/test_check_func_test.go
Labels: size/XL

#212 Add support for adding Authority Key ID to `tls_self_signed_cert`
  docs/resources/self_signed_cert.md
  internal/provider/common_cert.go
  internal/provider/fixtures_test.go
  internal/provider/resource_locally_signed_cert_test.go
  internal/provider/resource_self_signed_cert.go
  internal/provider/resource_self_signed_cert_test.go
  internal/provider/test_check_func_test.go
Labels: size/L
