Repository hashicorp/terraform-provider-tls, pull requests merged in 2022-02, with the labels that each got.

#145 Setting CODEOWNERS to the @hashicorp/terraform-provider-devex Team
  .github/CODEOWNERS
Labels: size/XS

#148 fixes typo in `certficate`
  website/docs/index.html.markdown
Labels: documentation, size/XS

#153 Run acceptance tests against all the current minor versions of Terraform >= 0.12
  .github/workflows/test.yml
  internal/provider/resource_private_key_test.go
Labels: size/L

#151 `tls_private_key` resource: adding support for ED25519 key algorithm
  internal/openssh/lib.go
  internal/openssh/lib_test.go
  internal/provider/data_source_public_key.go
  internal/provider/data_source_public_key_test.go
  internal/provider/resource_private_key.go
  internal/provider/resource_private_key_test.go
  internal/provider/types.go
  internal/provider/util.go
  website/docs/d/public_key.html.md
  website/docs/r/private_key.html.md
Labels: documentation, size/XL
