Repository hashicorp/terraform-provider-tls, pull requests merged in 2022-08, with the labels that each got.

#259 Bump minimum expected Go version to 1.18
  .github/workflows/test.yml
  .go-version
  go.mod
  go.sum
  internal/provider/data_source_certificate_test.go
  internal/provider/resource_locally_signed_cert_test.go
  internal/provider/testutils/test_check_func.go
Labels: dependencies, size/M

#265 .github/workflows: Use upstream pr-size-labeler and ignore go.sum
  .github/workflows/pull-request.yml
Labels: size/XS

#257 tls_cert_request not recreated when private_key_pem changes
  CHANGELOG.md
  go.mod
  go.sum
  internal/provider/common.go
  internal/provider/resource_cert_request_test.go
Labels: bug, dependencies, size/M
