Repository hashicorp/terraform-provider-tls, pull requests merged in 2023-03, with the labels that each got.

#330 Updating to Go 1.19
  .changes/unreleased/NOTES-20230303-164254.yaml
  .github/workflows/test.yml
  README.md
  go.mod
Labels: dependencies, size/XS, go

#335 .github/workflows: Test on Terraform 1.4.* versions
  .github/workflows/test.yml
Labels: size/XS

#337 Migrate acceptance tests to terraform-plugin-testing
  go.mod
  go.sum
  internal/provider/data_source_certificate_test.go
  internal/provider/data_source_public_key_test.go
  internal/provider/provider_test.go
  internal/provider/resource_cert_request_test.go
  internal/provider/resource_locally_signed_cert_test.go
  internal/provider/resource_private_key_test.go
  internal/provider/resource_self_signed_cert_test.go
  internal/provider/testutils/local_server.go
  internal/provider/testutils/test_check_func.go
Labels: dependencies, size/XS, technical-debt

#342 all: Replace custom default value plan modifiers with framework default handling
  internal/provider/attribute_plan_modifier_bool/default_value.go
  internal/provider/attribute_plan_modifier_int64/default_value.go
  internal/provider/attribute_plan_modifier_string/default_value.go
  internal/provider/resource_locally_signed_cert.go
  internal/provider/resource_private_key.go
  internal/provider/resource_self_signed_cert.go
Labels: size/L, technical-debt
