Repository hashicorp/terraform-provider-tls, pull requests merged in 2024-01, with the labels that each got.

#459 cdktf: update documentation
  docs/cdktf/python/data-sources/certificate.md
  docs/cdktf/python/data-sources/public_key.md
  docs/cdktf/python/index.md
  docs/cdktf/python/resources/cert_request.md
  docs/cdktf/python/resources/locally_signed_cert.md
  docs/cdktf/python/resources/private_key.md
  docs/cdktf/python/resources/self_signed_cert.md
  docs/cdktf/typescript/data-sources/certificate.md
  docs/cdktf/typescript/data-sources/public_key.md
  docs/cdktf/typescript/index.md
  docs/cdktf/typescript/resources/cert_request.md
  docs/cdktf/typescript/resources/locally_signed_cert.md
  docs/cdktf/typescript/resources/private_key.md
  docs/cdktf/typescript/resources/self_signed_cert.md
Labels: size/M

#460 Add `issues: write` permission to release workflow to close associated GitHub milestone
  .github/workflows/release.yml
Labels: size/XS

#463 cdktf: update documentation
  docs/cdktf/python/data-sources/certificate.md
  docs/cdktf/python/data-sources/public_key.md
  docs/cdktf/python/index.md
  docs/cdktf/python/resources/cert_request.md
  docs/cdktf/python/resources/locally_signed_cert.md
  docs/cdktf/python/resources/private_key.md
  docs/cdktf/python/resources/self_signed_cert.md
  docs/cdktf/typescript/data-sources/certificate.md
  docs/cdktf/typescript/data-sources/public_key.md
  docs/cdktf/typescript/index.md
  docs/cdktf/typescript/resources/cert_request.md
  docs/cdktf/typescript/resources/locally_signed_cert.md
  docs/cdktf/typescript/resources/private_key.md
  docs/cdktf/typescript/resources/self_signed_cert.md
Labels: size/XS

#466 .github/workflows: Update to hashicorp/ghaction-terraform-provider-release@v3
  .github/workflows/release.yml
Labels: size/XS

#470 Added GHA dependabot config for managing hashicorp actions
  .github/dependabot.yml
Labels: dependencies, size/XS
