Repository hashicorp/terraform-provider-tls, pull requests merged in 2025-04, with the labels that each got.

#608 Adding support of email field
  docs/resources/cert_request.md
  internal/provider/common_cert.go
  internal/provider/models.go
  internal/provider/resource_cert_request.go
Labels: size/XS

#642 chore: Fix CI test with terraform.io domain
  internal/provider/data_source_certificate_test.go
Labels: size/XS

#548 add support email address
  .changes/unreleased/ENHANCEMENTS-20250421-095025.yaml
  .changes/unreleased/ENHANCEMENTS-20250421-095051.yaml
  docs/resources/cert_request.md
  docs/resources/self_signed_cert.md
  internal/provider/common_cert.go
  internal/provider/resource_cert_request.go
  internal/provider/resource_cert_request_test.go
  internal/provider/resource_self_signed_cert.go
  internal/provider/resource_self_signed_cert_test.go
  internal/provider/testutils/test_check_func.go
Labels: enhancement, size/L

#644 Add CRT files and prepare for upcoming `4.1.0` release
  .changes/4.1.0.md
  .changes/unreleased/ENHANCEMENTS-20250421-095025.yaml
  .changes/unreleased/ENHANCEMENTS-20250421-095051.yaml
  .changes/unreleased/FEATURES-20250421-161314.yaml
  .changes/unreleased/NOTES-20250421-161320.yaml
  .copywrite.hcl
  .github/workflows/build.yml
  .release/ci.hcl
  .release/release-metadata.hcl
  .release/security-scan.hcl
  .release/terraform-provider-tls-artifacts.hcl
  CHANGELOG.md
  META.d/_summary.yaml
  version/VERSION
Labels: size/XL

#646 chore: Final onboarding to CRT
  .copywrite.hcl
  .github/workflows/release.yml
  .goreleaser.yml
  README.md
Labels: size/L
